apiVersion: v1
items:
- apiVersion: podsnapshot.gke.io/v1
  kind: PodSnapshotStorageConfig
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"podsnapshot.gke.io/v1","kind":"PodSnapshotStorageConfig","metadata":{"annotations":{},"name":"sandbox-snapshot-storage"},"spec":{"snapshotStorageConfig":{"gcs":{"bucket":"gke-ai-eco-dev-sbx-snapshots-us-central1","path":"m2-ladder"}}}}
    creationTimestamp: "2026-08-30T21:30:02Z"
    generation: 1
    name: sandbox-snapshot-storage
    resourceVersion: "1788125402524143001"
    uid: 3e6b8594-8547-4495-9342-65687a63227f
  spec:
    snapshotStorageConfig:
      gcs:
        bucket: gke-ai-eco-dev-sbx-snapshots-us-central1
        path: m2-ladder
        tokenSource: podKSA
  status:
    conditions:
    - lastTransitionTime: "2026-08-30T21:30:02Z"
      message: Valid PodSnapshotStorageConfig
      reason: StorageConfigValid
      status: "True"
      type: Ready
    observedGeneration: 1
- apiVersion: podsnapshot.gke.io/v1
  kind: PodSnapshotPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"podsnapshot.gke.io/v1","kind":"PodSnapshotPolicy","metadata":{"annotations":{},"name":"sandbox-snapshot-policy","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"python-snapshot-pool"}},"snapshotGroupingRules":{"groupByLabelValue":{"groupRetentionPolicy":{"maxSnapshotCountPerGroup":3},"labels":["agents.x-k8s.io/sandbox-name-hash"]}},"storageConfigName":"sandbox-snapshot-storage","triggerConfig":{"postCheckpoint":"resume","type":"manual"}}}
    creationTimestamp: "2026-08-30T21:26:38Z"
    generation: 1
    name: sandbox-snapshot-policy
    namespace: default
    resourceVersion: "1788125402562607012"
    uid: 37311414-6c22-4482-b8bf-c119ac574ebf
  spec:
    selector:
      matchLabels:
        app: python-snapshot-pool
    snapshotGroupingRules:
      groupByLabelValue:
        groupRetentionPolicy:
          maxSnapshotCountPerGroup: 3
        labels:
        - agents.x-k8s.io/sandbox-name-hash
    snapshotScope: whole-pod
    storageConfigName: sandbox-snapshot-storage
    triggerConfig:
      postCheckpoint: resume
      type: manual
  status:
    conditions:
    - lastTransitionTime: "2026-08-30T21:26:38Z"
      message: Policy specification is supported
      reason: PolicySpecSupported
      status: "True"
      type: PolicySpecSupported
    - lastTransitionTime: "2026-08-30T21:30:02Z"
      message: The referenced PodSnapshotStorageConfig "sandbox-snapshot-storage"
        was found
      reason: StorageConfigValid
      status: "True"
      type: StorageConfigValid
    - lastTransitionTime: "2026-08-30T21:30:02Z"
      message: The referenced PodSnapshotStorageConfig "sandbox-snapshot-storage"
        was found
      reason: StorageConfigValid
      status: "True"
      type: Ready
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
