import ray
import time
from k8s_agent_sandbox import SandboxClient
from k8s_agent_sandbox.models import SandboxLocalTunnelConnectionConfig

# Initialize a local Ray cluster for the PoC.
# In a production environment with KubeRay, this script would run inside the cluster.
ray.init()

@ray.remote
class RLEnvironmentWorker:
    def __init__(self, template_name: str, pool_name: str):
        print("Initializing RL Environment Worker...")
        
        # --- THE PRODUCTION-GRADE EXTERNAL CONFIG ---
        # Instead of port-forwarding, the SDK will automatically query the K8s API 
        # for the 'external-http-gateway' IP and route all HTTP traffic through it.
        from k8s_agent_sandbox.models import SandboxGatewayConnectionConfig
        
        config = SandboxGatewayConnectionConfig(
            gateway_name="external-http-gateway",
            gateway_namespace="default",
            server_port=8888
        )
        
        self.client = SandboxClient(connection_config=config, cleanup=True)
        
        # The rest of your claiming logic remains identical
        self.sandbox = self.client.create_sandbox(
            template=template_name,
            warmpool=pool_name,
            shutdown_after_seconds=3600
        )
        print(f"Environment ready via Gateway: {self.sandbox.claim_name}")

    def step(self, action_code: str):
        """
        The core RL step function.
        - Action: The untrusted code generated by the AI agent.
        - Observation: What the code output to stdout/stderr.
        - Reward: +1.0 for solving the task, -1.0 for errors or destructive behavior.
        """
        # 1. Apply the Agent's action to the environment
        self.sandbox.files.write("agent_action.py", action_code)
        result = self.sandbox.commands.run("python agent_action.py", timeout=5)
        
        # 2. Formulate the Observation
        observation = {
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
            "exit_code": result.exit_code
        }

        # 3. Calculate the Reward (Task: Calculate the 10th Fibonacci number)
        reward = 0.0
        done = False
        
        if result.exit_code == 0 and "55" in result.stdout:
            reward = 1.0  # Success!
            done = True
        elif result.exit_code != 0:
            reward = -1.0 # Penalize syntax errors or crashes
            
        return observation, reward, done

    def teardown(self):
        """Cleans up the SandboxClaim in Kubernetes."""
        self.client.delete_all()

# ==========================================
# --- Simulated Agentic RL Training Loop ---
# ==========================================

print("Spawning Ray RL Environment Worker...")
env_worker = RLEnvironmentWorker.remote(template_name="ray-python-template", pool_name="ray-pool")

# --- Episode 1: The Exploration Phase (Malicious/Destructive Action) ---
print("\n[Episode 1] Agent attempts a destructive action during exploration...")
destructive_action = """
import os
print('Attempting to delete files...')
os.system('rm -rf /app/*')
raise Exception('Self-destructing the agent!')
"""

future_1 = env_worker.step.remote(destructive_action)
obs_1, reward_1, done_1 = ray.get(future_1)

print(f"Observation (Exit {obs_1['exit_code']}): {obs_1['stderr']}")
print(f"Reward: {reward_1} | Done: {done_1}")
print("Result: Sandbox contained the destruction. Ray worker remains healthy.")

# --- Episode 2: The Exploitation Phase (Correct Action) ---
print("\n[Episode 2] Agent learns and attempts the correct coding action...")
correct_action = """
def fibonacci(n):
    if n <= 0: return 0
    elif n == 1: return 1
    else: return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(10))
"""

future_2 = env_worker.step.remote(correct_action)
obs_2, reward_2, done_2 = ray.get(future_2)

print(f"Observation (Exit {obs_2['exit_code']}): {obs_2['stdout']}")
print(f"Reward: {reward_2} | Done: {done_2}")
print("Result: Agent successfully solved the task securely.")

# Cleanup resources
env_worker.teardown.remote()
time.sleep(2) # Allow time for K8s deletion commands to fire over the network
ray.shutdown()